import json, random, textwrap, os
from xml.sax.saxutils import escape as esc
random.seed(7)
# id, en, ar, blurb_en, blurb_ar, color, shape
CATS = [
 (1,"Pain & Fever","مسكنات وخافضات حرارة","Relief from headache, fever and general pain.","لتسكين الصداع والحرارة والآلام العامة.","#c2410c","box","🌡️"),
 (2,"Cold, Cough & Flu","برد وكحة وأنفلونزا","Care for colds, sore throat, cough and blocked nose.","للعناية بالبرد والتهاب الحلق والكحة وانسداد الأنف.","#0369a1","bottle","🤧"),
 (3,"Antibiotics","مضادات حيوية","Prescription-only antibiotics for bacterial infections.","مضادات حيوية لا تُصرف إلا بروشتة.","#7c3aed","box","🧫"),
 (4,"Digestive Health","الجهاز الهضمي","Stomach, acidity, bowel and digestion support.","لمشاكل المعدة والحموضة والقولون والهضم.","#15803d","box","🫃"),
 (5,"Allergy","الحساسية","Relief from allergic rhinitis, itching and hives.","لعلاج حساسية الأنف والحكة والارتيكاريا.","#db2777","box","🌼"),
 (6,"Diabetes","السكر","Treatments for type 1 and type 2 diabetes.","أدوية لمرضى السكر من النوع الأول والثاني.","#1d4ed8","box","🩸"),
 (7,"Heart & Blood Pressure","القلب والضغط","Medicines for blood pressure, cholesterol and heart care.","أدوية الضغط والكوليسترول ورعاية القلب.","#b91c1c","box","❤️"),
 (8,"Vitamins & Supplements","فيتامينات ومكملات","Daily vitamins, minerals and nutritional supplements.","فيتامينات ومعادن ومكملات غذائية يومية.","#ca8a04","bottle","🍊"),
 (9,"Skin Care & Dermatology","العناية بالبشرة والجلدية","Creams and treatments for skin conditions and daily care.","كريمات وعلاجات للمشاكل الجلدية والعناية اليومية.","#0f766e","tube","🧴"),
 (10,"Eye, Ear & Nose","عيون وأذن وأنف","Drops and sprays for eyes, ears and nose.","قطرات وبخاخات للعين والأذن والأنف.","#0891b2","bottle","👁️"),
 (11,"Mother & Baby","الأم والطفل","Baby milk, diapers, skin care and mother essentials.","ألبان وحفاضات وعناية بالطفل ومستلزمات الأم.","#e11d48","bottle","👶"),
 (12,"Personal Care","العناية الشخصية","Oral care, hair care, hygiene and daily essentials.","عناية بالفم والشعر ونظافة شخصية ومستلزمات يومية.","#4f46e5","tube","🪥"),
 (13,"First Aid","إسعافات أولية","Antiseptics, dressings and wound care.","مطهرات وضمادات وعناية بالجروح.","#dc2626","bottle","🩹"),
 (14,"Medical Devices","أجهزة طبية","Home monitors, thermometers, nebulizers and supports.","أجهزة قياس منزلية وترمومترات وأجهزة بخار ودعامات.","#334155","device","🩺"),
 (15,"Cosmetics","مستحضرات تجميل","Skin, sun and beauty products from trusted brands.","منتجات بشرة وواقي شمس وتجميل من ماركات موثوقة.","#be185d","jar","💄"),
 (16,"Muscles & Joints","العضلات والمفاصل","Gels, sprays and tablets for muscle and joint pain.","جيل وسبراي وأقراص لآلام العضلات والمفاصل.","#9a3412","tube","🦴"),
]
# en, ar, active ingredient, price EGP, needs prescription
D = {
1:[("Panadol Extra","بنادول إكسترا","Paracetamol + Caffeine",48,0),("Panadol Advance","بنادول أدفانس","Paracetamol",42,0),("Adol 500","أدول 500","Paracetamol",28,0),("Fevadol 500","فيفادول 500","Paracetamol",25,0),("Cataflam 50","كتافلام 50","Diclofenac potassium",62,0),("Brufen 400","بروفين 400","Ibuprofen",38,0),("Ponstan 500","بونستان 500","Mefenamic acid",55,0),("Nurofen 200","نوروفين 200","Ibuprofen",70,0),("Abimol 500","أبيمول 500","Paracetamol",24,0),("Paramol Syrup","بارامول شراب","Paracetamol",32,0)],
2:[("Comtrex","كومتركس","Paracetamol + Chlorpheniramine + Pseudoephedrine",35,0),("Antiflu Capsules","أنتي فلو كبسول","Paracetamol + Pseudoephedrine",30,0),("Flumucil 600","فلوميوسيل 600","Acetylcysteine",75,0),("Mucosolvan Syrup","موكوسولفان شراب","Ambroxol",58,0),("Otrivin Nasal Spray","أوتريفين بخاخ أنف","Xylometazoline",52,0),("Strepsils Lozenges","ستربسلز أقراص مص","Amylmetacresol + Dichlorobenzyl alcohol",45,0),("Prospan Syrup","بروسبان شراب","Ivy leaf extract",110,0),("Vicks VapoRub","فيكس فابوراب","Menthol + Camphor + Eucalyptus oil",40,0),("Decolgen","ديكولجين","Paracetamol + Phenylephrine",22,0),("Sinecod Syrup","سينكود شراب","Butamirate citrate",68,0)],
3:[("Augmentin 1g","أوجمنتين 1 جم","Amoxicillin + Clavulanic acid",145,1),("Amoxil 500","أموكسيل 500","Amoxicillin",48,1),("Zithromax 500","زيثروماكس 500","Azithromycin",135,1),("Ciprofar 500","سيبروفار 500","Ciprofloxacin",60,1),("Flagyl 500","فلاجيل 500","Metronidazole",30,1),("Klacid 500","كلاسيد 500","Clarithromycin",170,1),("Suprax 400","سوبراكس 400","Cefixime",125,1),("Zinnat 500","زينات 500","Cefuroxime",160,1),("Tavanic 500","تافانيك 500","Levofloxacin",190,1),("Doxycycline 100","دوكسيسيكلين 100","Doxycycline",28,1)],
4:[("Antinal","أنتينال","Nifuroxazide",32,0),("Buscopan","بوسكوبان","Hyoscine butylbromide",42,0),("Gaviscon Liquid","جافيسكون سائل","Sodium alginate + Sodium bicarbonate",85,0),("Nexium 40","نيكسيوم 40","Esomeprazole",195,0),("Controloc 40","كونترولوك 40","Pantoprazole",120,0),("Motilium","موتيليوم","Domperidone",45,0),("Duphalac Syrup","دوفالاك شراب","Lactulose",78,0),("Smecta","سمكتا","Diosmectite",50,0),("Enterogermina","إنتيروجرمينا","Bacillus clausii",88,0),("Maalox Suspension","مالوكس معلق","Aluminium hydroxide + Magnesium hydroxide",52,0)],
5:[("Claritin 10mg","كلاريتين 10 مجم","Loratadine",44,0),("Zyrtec 10mg","زيرتك 10 مجم","Cetirizine",55,0),("Telfast 120","تلفاست 120","Fexofenadine",105,0),("Aerius 5mg","إيريوس 5 مجم","Desloratadine",98,0),("Xyzal 5mg","زيزال 5 مجم","Levocetirizine",90,0),("Flixonase Nasal Spray","فليكسوناز بخاخ أنف","Fluticasone propionate",140,0),("Nasonex Nasal Spray","ناسونكس بخاخ أنف","Mometasone furoate",185,1),("Zaditen","زاديتين","Ketotifen",36,0)],
6:[("Glucophage 500","جلوكوفاج 500","Metformin",32,1),("Diamicron MR 60","ديامكرون إم آر 60","Gliclazide",98,1),("Amaryl 2mg","أماريل 2 مجم","Glimepiride",75,1),("Januvia 100","جانوفيا 100","Sitagliptin",420,1),("Galvus 50","جالفوس 50","Vildagliptin",360,1),("Forxiga 10","فورسيجا 10","Dapagliflozin",480,1),("Jardiance 25","جارديانس 25","Empagliflozin",510,1),("Lantus SoloStar","لانتوس سولوستار","Insulin glargine",620,1),("Novorapid FlexPen","نوفورابيد فليكس بن","Insulin aspart",540,1)],
7:[("Concor 5","كونكور 5","Bisoprolol",88,1),("Norvasc 5","نورفاسك 5","Amlodipine",70,1),("Lipitor 20","ليبيتور 20","Atorvastatin",210,1),("Crestor 10","كريستور 10","Rosuvastatin",235,1),("Aspirin Protect 100","أسبرين بروتكت 100","Acetylsalicylic acid",45,0),("Plavix 75","بلافيكس 75","Clopidogrel",280,1),("Co-Diovan 80/12.5","كو ديوفان 80/12.5","Valsartan + Hydrochlorothiazide",165,1),("Lasix 40","لازكس 40","Furosemide",24,1),("Xarelto 20","زاريلتو 20","Rivaroxaban",640,1),("Tritace 5","تريتاس 5","Ramipril",95,1)],
8:[("Centrum Adults","سنتروم للبالغين","Multivitamins + Minerals",280,0),("Redoxon Vitamin C","ريدوكسون فيتامين سي","Vitamin C",95,0),("Neurobion","نيوروبيون","Vitamin B1 + B6 + B12",60,0),("Feroglobin Capsules","فيروجلوبين كبسول","Iron + Vitamins",130,0),("Vidrop D3 Drops","فيدروب د3 نقط","Cholecalciferol",52,0),("Omega-3 Fish Oil 1000","أوميجا 3 زيت سمك 1000","EPA + DHA",220,0),("Caltrate Plus","كالتريت بلس","Calcium + Vitamin D",175,0),("Zinc 50mg","زنك 50 مجم","Zinc",65,0),("Magnesium B6","ماغنسيوم ب6","Magnesium + Vitamin B6",110,0),("Biotin 10000mcg","بيوتين 10000","Biotin",150,0),("Pharmaton","فارماتون","Ginseng + Multivitamins",240,0)],
9:[("Bepanthen Ointment","بيبانثين مرهم","Dexpanthenol",65,0),("Fucicort Cream","فيوسيكورت كريم","Fusidic acid + Betamethasone",58,0),("Canesten Cream","كانيستين كريم","Clotrimazole",72,0),("Lamisil Cream","لاميزيل كريم","Terbinafine",95,0),("Cetaphil Moisturizing Lotion","سيتافيل مرطب لوشن","Glycerin + Niacinamide",310,0),("Eucerin Urea Repair Cream","يوسيرين يوريا كريم","Urea 5%",290,0),("Differin Gel","ديفرين جيل","Adapalene",255,1),("Benzac AC 5%","بنزاك إيه سي 5%","Benzoyl peroxide",120,0),("Elocon Cream","إيلوكون كريم","Mometasone furoate",80,1)],
10:[("Systane Ultra Eye Drops","سيستان ألترا قطرة عين","Polyethylene glycol + Propylene glycol",210,0),("Optive Eye Drops","أوبتيف قطرة عين","Carboxymethylcellulose + Glycerin",195,0),("Hylo-Comod Eye Drops","هيلو كومود قطرة عين","Sodium hyaluronate",230,0),("Visine Eye Drops","فيزين قطرة عين","Tetrahydrozoline",48,0),("Tobradex Eye Drops","توبرادكس قطرة عين","Tobramycin + Dexamethasone",85,1),("Ciloxan Eye Drops","سيلوكسان قطرة عين","Ciprofloxacin",70,1),("Otipax Ear Drops","أوتيباكس قطرة أذن","Phenazone + Lidocaine",60,1),("Sterimar Nasal Spray","ستيريمار بخاخ أنف","Sterile seawater",140,0)],
11:[("Aptamil 1 Infant Milk","أبتاميل 1 لبن أطفال","Infant formula 0-6 months",330,0),("Nan Optipro 1","نان أوبتيبرو 1","Infant formula 0-6 months",310,0),("Pampers Baby-Dry Size 4","بامبرز بيبي دراي مقاس 4","Diapers 9-14 kg",260,0),("Huggies Extra Care Size 3","هاجيز إكسترا كير مقاس 3","Diapers 5-9 kg",240,0),("Pampers Sensitive Wipes","بامبرز مناديل حساسة","Baby wipes",75,0),("Johnson's Baby Shampoo","جونسون شامبو أطفال","Gentle baby shampoo",90,0),("Sudocrem","سودوكريم","Zinc oxide",110,0),("Infacol Drops","إنفاكول نقط","Simethicone",85,0),("Mustela Hydra Bebe Lotion","موستيلا هيدرا بيبي لوشن","Baby body lotion",380,0),("Nursing Pads","وسادات رضاعة","Disposable breast pads",95,0)],
12:[("Sensodyne Repair & Protect","سنسوداين ريبير آند بروتكت","Toothpaste for sensitive teeth",135,0),("Signal Complete 8","سيجنال كومبليت 8","Toothpaste",42,0),("Listerine Cool Mint","ليسترين كول مينت","Mouthwash",88,0),("Colgate Total","كولجيت توتال","Toothpaste",55,0),("Head & Shoulders Classic","هيد آند شولدرز كلاسيك","Anti-dandruff shampoo",120,0),("Dove Original Deodorant","دوف مزيل عرق أوريجينال","Antiperspirant",78,0),("Always Ultra Normal","أولويز ألترا عادي","Sanitary pads",48,0),("Gillette Fusion Razor","جيليت فيوجن ماكينة حلاقة","Razor with blades",320,0),("Oral-B Floss","أورال بي خيط أسنان","Dental floss",65,0),("Vaseline Lip Therapy","فازلين مرطب شفاه","Lip balm",38,0)],
13:[("Betadine Solution","بيتادين محلول","Povidone-iodine",48,0),("Dettol Antiseptic","ديتول مطهر","Chloroxylenol",65,0),("Hydrogen Peroxide 3%","ماء أكسجين 3%","Hydrogen peroxide",12,0),("Band-Aid Plasters","بلاستر باند إيد","Adhesive plasters",35,0),("Sterile Gauze Pads","شاش معقم","Sterile gauze",22,0),("Medical Cotton 100g","قطن طبي 100 جم","Absorbent cotton",28,0),("Elastic Bandage 10cm","رباط ضاغط 10 سم","Elastic bandage",30,0),("Micropore Tape","شريط لاصق ميكروبور","Hypoallergenic tape",34,0),("Flammazine Cream","فلامازين كريم","Silver sulfadiazine",92,1),("Antiseptic Alcohol 70%","كحول طبي 70%","Ethyl alcohol",20,0)],
14:[("Omron M2 Blood Pressure Monitor","أومرون M2 جهاز ضغط","Upper-arm digital monitor",1450,0),("Accu-Chek Active Glucometer","أكيو تشيك أكتيف جهاز سكر","Blood glucose meter",780,0),("Accu-Chek Active Strips x50","أكيو تشيك أكتيف شرائط 50","Glucose test strips",420,0),("Omron Digital Thermometer","أومرون ترمومتر ديجيتال","Digital thermometer",120,0),("Fingertip Pulse Oximeter","جهاز قياس الأكسجين بالإصبع","SpO2 and pulse monitor",450,0),("Omron C101 Nebulizer","أومرون C101 جهاز بخار","Compressor nebulizer",1850,0),("Oral-B Pro 1000","أورال بي برو 1000","Electric toothbrush",1300,0),("Knee Support Brace","دعامة ركبة","Elastic knee support",240,0),("Digital Bathroom Scale","ميزان حمام ديجيتال","Body weight scale",350,0),("Heating Pad","وسادة تدفئة كهربائية","Electric heating pad",380,0)],
15:[("Nivea Soft Cream","نيفيا سوفت كريم","Light moisturizing cream",85,0),("Vaseline Petroleum Jelly","فازلين جيلي","Petroleum jelly",48,0),("La Roche-Posay Anthelios SPF50","لا روش بوزيه أنثيليوس SPF50","Sunscreen",620,0),("Bioderma Sensibio H2O","بيوديرما سنسيبيو H2O","Micellar water",410,0),("Vichy Mineral 89","فيشي مينرال 89","Hyaluronic acid booster",780,0),("Garnier Micellar Water","جارنييه ميسيلار ووتر","Micellar cleansing water",145,0),("L'Oreal Revitalift Night Cream","لوريال ريفيتاليفت كريم ليلي","Anti-ageing night cream",360,0),("Neutrogena Hydro Boost Gel","نيوتروجينا هيدرو بوست جيل","Hyaluronic acid gel cream",395,0),("The Ordinary Niacinamide 10% + Zinc 1%","ذا أوردينري نياسيناميد 10% + زنك 1%","Niacinamide + Zinc",430,0),("Eucerin Sun SPF50+","يوسيرين صن SPF50+","Sunscreen",560,0)],
16:[("Voltaren Emulgel","فولتارين إمولجيل","Diclofenac diethylamine",95,0),("Fastum Gel","فاستم جيل","Ketoprofen",88,0),("Deep Heat Spray","ديب هيت سبراي","Menthol + Methyl salicylate",72,0),("Tiger Balm","تايجر بالم","Camphor + Menthol",45,0),("Decontractyl","ديكونتراكتيل","Mephenesin",52,1),("Voltfast 50","فولتفاست 50","Diclofenac potassium",66,0),("Arcoxia 90","أركوكسيا 90","Etoricoxib",170,1),("Rheumon Gel","روميون جيل","Etofenamate",60,0),("Glucosamine 1500 Sulfate","جلوكوزامين 1500","Glucosamine sulfate",210,0)],
}
def svg(name, sub, color, shape):
    dark="#16302c"
    if shape=="box": body=f'<rect x="105" y="60" width="190" height="275" rx="14" fill="{color}"/><rect x="105" y="60" width="190" height="62" rx="14" fill="#fff" fill-opacity=".2"/>'
    elif shape=="bottle": body=f'<rect x="160" y="42" width="80" height="44" rx="8" fill="{dark}"/><rect x="120" y="82" width="160" height="253" rx="34" fill="{color}"/>'
    elif shape=="tube": body=f'<rect x="125" y="50" width="150" height="262" rx="22" fill="{color}"/><rect x="160" y="308" width="80" height="44" rx="8" fill="{dark}"/>'
    elif shape=="jar": body=f'<rect x="95" y="105" width="210" height="52" rx="12" fill="{dark}"/><rect x="105" y="150" width="190" height="185" rx="24" fill="{color}"/>'
    else: body=f'<rect x="95" y="80" width="210" height="250" rx="30" fill="{color}"/><rect x="122" y="106" width="156" height="84" rx="12" fill="{dark}"/><circle cx="200" cy="285" r="22" fill="#fff" fill-opacity=".85"/>'
    cross='' if shape=="device" else f'<rect x="193" y="76" width="14" height="34" rx="3" fill="#fff"/><rect x="183" y="86" width="34" height="14" rx="3" fill="#fff"/>'
    if shape=="device": cross='<rect x="170" y="140" width="60" height="8" rx="4" fill="#4ade80"/>'
    lines=textwrap.wrap(name,14)[:2]
    y0=222 if shape!="device" else 240
    txt=''.join(f'<text x="200" y="{y0+i*25}" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="21" fill="#fff">{esc(l)}</text>' for i,l in enumerate(lines))
    s=textwrap.shorten(sub,24,placeholder="…")
    txt+=f'<text x="200" y="{y0+len(lines)*25+10}" text-anchor="middle" font-family="Arial,sans-serif" font-size="13" fill="#fff" fill-opacity=".85">{esc(s)}</text>'
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><rect width="400" height="400" fill="#eef6f4"/><ellipse cx="200" cy="362" rx="110" ry="12" fill="#000" fill-opacity=".08"/>{body}{cross}{txt}</svg>'
cats=[];prods=[];pid=0
for c in CATS:
    cid,en,ar,be,ba,col,shape,icon=c
    cats.append({"id":cid,"name":en,"nameAr":ar,"icon":icon})
    for i,(pe,pa,act,price,rx) in enumerate(D[cid]):
        pid+=1
        stock=0 if random.random()<.06 else random.randint(8,120)
        open(f"../public/img/products/{pid}.svg","w").write(svg(pe,act,col,shape))
        prods.append({"id":pid,"name":pe,"nameAr":pa,"category":cid,"active":act,"price":price,"stock":stock,"rx":bool(rx),
          "featured":i==0 and cid in (1,2,5,8,9,11,12,15),"image":f"/img/products/{pid}.svg",
          "desc":f"{pe} — {act}. {be}","descAr":f"{pa} — {act}. {ba}"})
open("../public/img/default.svg","w").write(svg("Product","", "#0e4f47","box"))
db={"users":[{"id":1,"name":"Admin","email":"admin@pharma.com","password":"Admin123","phone":"01000000000","address":"Cairo","role":"admin"},
 {"id":2,"name":"Demo User","email":"user@pharma.com","password":"User1234","phone":"01012345678","address":"Nasr City, Cairo","role":"user"}],
 "categories":cats,"products":prods,"orders":[],"prescriptions":[],"messages":[]}
json.dump(db,open("db.json","w"),ensure_ascii=False,indent=1)
print(len(prods),"products",len(cats),"categories")
